Netsweeper/Netsweeper/urls.py
from django.conf.urls import include, url
from django.contrib import admin

admin.site.site_header = 'Netsweeper Competitors Database Admin'
admin.site.site_title = 'Netsweeper Competitors'

urlpatterns = [
    url(r'^admin/', include(admin.site.urls), name='admin'),
    url(r'^', include('NetsweeperCompetitors.urls')),
]

Netsweeper/NetsweeperCompetitors/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^globalmarket/$', views.globalmarket, name='globalmarket'),
    url(r'^verticalmarket/$', views.verticalmarket, name='verticalmarket'),
    url(r'^technology/$', views.technology, name='technology'),
    url(r'^channels/$', views.channels, name='channels'),
    url(r'^revenue/$', views.revenue, name='revenue'),
    url(r'^features/$', views.features, name='features'),
    url(r'^categories/$', views.categories, name='categories'),
    url(r'^details/$', views.details, name='details'),
    url(r'^print/$', views.printpage, name='printpage'),
    url(r'^competitordocs/$', views.competitordocs, name='competitordocs'),
    url(r'^salesdocs/$', views.salesdocs, name='salesdocs'),
    url(r'^change/$', views.changepassword, name='changepassword')
]

Netsweeper/NetsweeperCompetitors/models.py
from django.db import models


class CompetitorDataSource(models.Model):
    name = models.CharField("Data Source Name",
                            max_length=255,
                            blank=False)

    def __str__(self):
        return self.name


class Feature(models.Model):
    name = models.CharField(max_length=255, blank=False)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255, blank=False)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class GlobalMarket(models.Model):
    name = models.CharField(max_length=255, blank=False)

    def __str__(self):
        return self.name


class VerticalMarket(models.Model):
    name = models.CharField(max_length=255, blank=False)

    def __str__(self):
        return self.name


class TargetMarket(models.Model):
    name = models.CharField(max_length=255, blank=False)

    class Meta:
        verbose_name_plural = "Target Market"
        verbose_name = "Target Market"

    def __str__(self):
        return self.name


class Competitor(models.Model):
    dataSource = models.ManyToManyField(CompetitorDataSource,
                                        verbose_name="Competitor Data Sources")
    target_Market = models.ManyToManyField(TargetMarket,
                                           verbose_name="Target Markets")
    features = models.ManyToManyField(Feature,
                                      through='CompanyFeatures')
    categories = models.ManyToManyField(Category,
                                        through='CompetitorCategories')
    globalMarket = models.ManyToManyField(GlobalMarket,
                                          through='GlobalMarketShare')
    verticalMarket = models.ManyToManyField(VerticalMarket,
                                            through='VerticalMarketShare')
    name = models.CharField("Company Name",
                            max_length=255,
                            blank=False)
    acquired = models.BooleanField("Acquired")
    acquired_by = models.CharField(max_length=255,
                                   blank=True)
    merged_with = models.CharField(max_length=255,
                                   blank=True)
    channel_partners = models.TextField("Channel Partners",
                                        max_length=5000,
                                        blank=True)
    technology_partners = models.TextField("Technology Partners",
                                           max_length=5000,
                                           blank=True)
    oem_partners = models.TextField("OEM Partners",
                                    max_length=5000,
                                    blank=True)
    status = models.TextField("Company Status",
                              max_length=1000,
                              blank=True)
    focus = models.TextField("Company Focus",
                             max_length=3000,
                             blank=True)
    url = models.URLField("Website",
                          max_length=255,
                          blank=True)
    saas = models.DecimalField("SaaS",
                               blank=True,
                               null=False,
                               default=0,
                               decimal_places=2,
                               max_digits=12,
                               help_text="Enter in format: 00.00")
    direct = models.IntegerField("Direct",
                                 blank=True,
                                 null=False,
                                 default=0)
    partners = models.IntegerField(blank=True,
                                   null=False,
                                   default=0)
    appliance = models.DecimalField(blank=True,
                                    null=False,
                                    default=0,
                                    decimal_places=2,
                                    max_digits=12,
                                    help_text="Enter in format: 00.00")
    notes = models.TextField("Notes",
                             max_length=3000,
                             blank=True)
    strengths = models.TextField("Strengths",
                                 max_length=3000,
                                 blank=True)
    weaknesses = models.TextField("Weaknesses",
                                  max_length=3000,
                                  blank=True)
    number_of_categories = models.IntegerField(blank=True,
                                               null=False,
                                               default=0)
    last_updated = models.DateTimeField("Last Updated", auto_now=True)

    def __str__(self):
        return self.name


class CompetitorCategories(models.Model):
    competitor = models.ForeignKey(Competitor)
    category = models.ForeignKey(Category)
    details = models.TextField("Sub-Categories",
                               blank=True,
                               null=True,
                               max_length=3000)

    class Meta:
        verbose_name_plural = "Competitor Filtering Categories"


class Platform(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Installation(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Product(models.Model):
    competitor = models.ForeignKey(Competitor)
    name = models.CharField(max_length=255,
                            blank=False)
    status = models.TextField(max_length=3000,
                              blank=True)
    platform = models.ManyToManyField(Platform,
                                      blank=True)
    installation = models.ManyToManyField(Installation,
                                          blank=True)
    urlDB = models.CharField("URL Database",
                             max_length=255,
                             blank=True)
    price = models.DecimalField(blank=True,
                                null=False,
                                default=0,
                                decimal_places=2,
                                max_digits=12,
                                help_text="Enter in format: 00.00")
    notes = models.TextField(max_length=3000,
                             blank=True)

    def __str__(self):
        return self.name


class Review(models.Model):
    competitor = models.ForeignKey(Competitor)
    review = models.TextField(max_length=255,
                              blank=True)


class RevenueDataSource(models.Model):
    name = models.CharField("Data Source Name",
                            max_length=255,
                            blank=False)

    def __str__(self):
        return self.name


class AdditionalInfo(models.Model):
    competitor = models.ForeignKey(Competitor)
    document_name = models.CharField("Document Name",
                                     max_length=255,
                                     blank=False)
    document = models.FileField("Add extra documentation")
    description = models.TextField("Description",
                                   max_length=3000,
                                   blank=True)

    class Meta:
        verbose_name_plural = "Additional Info"

    def __str__(self):
        return self.competitor.name


class RevenueEstimate(models.Model):
    competitor = models.ForeignKey(Competitor)
    dataSource = models.ForeignKey(RevenueDataSource)
    totalRevenue = models.DecimalField("Estimated Total Revenue (millions)",
                                       blank=True,
                                       null=False,
                                       default=0,
                                       decimal_places=2,
                                       max_digits=12,
                                       help_text="Enter in format: 00.00")
    filteringRevenue = models.DecimalField("Estimated Filtering Revenue (millions)",
                                           blank=True,
                                           null=False,
                                           default=0,
                                           decimal_places=2,
                                           max_digits=12,
                                           help_text="Enter in format: 00.00")


class CompanyFeatures(models.Model):
    competitor = models.ForeignKey(Competitor)
    feature = models.ForeignKey(Feature)
    featureSpecs = models.TextField("Technical Details",
                                    blank=True,
                                    null=True,
                                    max_length=3000)

    class Meta:
        verbose_name_plural = "Product Features"


class GlobalMarketShare(models.Model):
    competitor = models.ForeignKey(Competitor)
    global_market = models.ForeignKey(GlobalMarket)
    share = models.DecimalField(blank=True,
                                null=False,
                                default=0,
                                decimal_places=2,
                                max_digits=12,
                                help_text="Enter in format: 00.00")


class VerticalMarketShare(models.Model):
    competitor = models.ForeignKey(Competitor)
    vertical_market = models.ForeignKey(VerticalMarket)
    share = models.DecimalField(blank=True,
                                null=False,
                                default=0,
                                decimal_places=2,
                                max_digits=12,
                                help_text="Enter in format: 00.00")


class ResourceCategory(models.Model):
    name = models.CharField("Resource Category",
                            max_length=255,
                            blank=False)
    description = models.TextField("Description",

Netsweeper/NetsweeperCompetitors/templates/NetsweeperCompetitors/categories.html
<!DOCTYPE html>
<html>

{% extends "NetsweeperCompetitors/navbar.html" %}
{% load dictionary_lookup %}
{% load set_var %}
{% load staticfiles %}


<head lang="en">
    <meta charset="UTF-8">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Netsweeper Competitors</title>
    {% block extrastyles %}

    {% endblock %}

</head>
<body>
{% block body %}
<div id="messages">
    <p class="bg-danger text-danger" align="center">{{ message }}</p>
    <p class="text-center small">Please note: Only competitors with valid data will be shown.</p>
    <p class="text-center small">Printing more than 3 company comparisons at once is not recommended.</p>
</div>

<div class="selectForm" align="center">
    <form method="POST" action="{% url 'categories' %}">
        {% csrf_token %}
        <div class="col-md-4 col-md-offset-2">
            {{ form.selection.errors }}<br>
            {{ form.selection.label_tag }}<br>
            {{ form.selection }}<br>
        </div>

        <div class="col-md-4">
            {{ form.categorySelect.errors }}<br>
            {{ form.categorySelect.label_tag }}<br>
            {{ form.categorySelect }}<br>
        </div>
        <div class="text-center col-md-12">
            <button type="submit" class="btn btn-lg btn-primary" id="formButtons">Submit</button>
            <a type="button" class="btn btn-lg btn-default" href="{% url 'categories' %}" id="formButtons">Clear Selections</a>
        </div>

    </form>
</div>

<div class="text-center col-md-12">
    <form>
        <button class="btn btn-lg btn-primary" onClick="window.print()">Print</button>
    </form>
</div>

{% if categories %}
<table class="table table-striped">
    <thead>
    <tr>
        <th></th>
        {% for key in categories %} <!--First -->

        <th class="text-center" style="border-left:1px solid #d3d3d3">

            <h4>{{ key }}</h4>

        </th>
        {% endfor %}<!--First -->
    </tr>
    </thead>

    <tr>
        <th class="text-right">
            <h4>Type</h4>
        </th>
        {% for key in categories %}
        <th style="border-left:1px solid #d3d3d3">
            <h4>Categories</h4>
        </th>
        {% endfor %}
    </tr>

    {% for name in category_names %} <!-- Second -->

    <tr>
        <th class="text-right">
            <p>{{ name.name }}</p>
        </th>
        {% for key in categories %}

        <td style="border-left:1px solid #d3d3d3" id="subcategories">
            {% for item in categories|get_item:key %}<!--Fifth -->
            {% if item.category__name == name.name %} <!--Second If -->
            {% if item.details %}<!--Third If -->
            <p>{{ item.details|linebreaks }}</p>
            {% endif %}<!--Third If -->
            {% endif %}<!--Second If -->
            {% endfor %}<!--Fifth -->
        </td>
        {% endfor %}<!-- Third -->
    </tr>
    {% endfor %}<!-- Second -->
</table>
{% endif %}
{% endblock %}
</body>

{% block extrajs %}
{% endblock %}

</html>

Netsweeper/NetsweeperCompetitors/templates/NetsweeperCompetitors/changepassword.html
<!DOCTYPE html>

<html>

{% extends "NetsweeperCompetitors/navbar.html" %}
<head lang="en">
    <meta charset="UTF-8">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Netsweeper Competitors</title>
    {% block extrastyles %}
    <style>
        .input-group-addon {
        background-color: #fff;
        }
        .merged input:first-child {
        border-right: 0px;
        }
        .merged .input-group-addon + input {
        border-left: 0px;
        }
    </style>
    {% endblock %}
</head>

<body>
{% block body %}
<h3 class="text-center">Change Password</h3>

<div class="col-md-4 col-md-offset-4">
    {% if success %}
    <p class="bg-primary text-primary text-center">{{ message|safe }}</p>
    <a href="{% url 'login' %}">Log back in</a>
    {% else %}
    <p class="bg-danger text-danger text-center">{{ message }}</p>
    {% endif %}
</div>

<div class="col-md-4 col-md-offset-4 text-center" style="padding-top: 2%">
    <form method="POST" action="{% url 'changepassword' %}">
        {{ form.old_password.errors }}
        {{ form.old_password.label_tag }}
        {{ form.old_password }}
        <div style="padding-top: 10%">
            {{ form.new_password.errors }}
            {{ form.new_password.label_tag }}
            <div class="input-group merged">
                {{ form.new_password }}
                <div class="input-group-addon"><span id="pwEnter" aria-hidden="true"></span></div>
            </div>
            {{ form.confirm_password.errors }}
            {{ form.confirm_password.label_tag }}
            <div class="input-group merged">
                {{ form.confirm_password }}
                <div class="input-group-addon"><span id="pwAlert" aria-hidden="true"></span></div>
            </div>
        </div>
        <div class="col-md-12">
            <button type="submit" class="btn btn-lg btn-primary" id="formButtons">Submit</button>
            <a type="button" class="btn btn-lg btn-default" href="{% url 'changepassword' %}" id="formButtons">Clear</a>
            {% csrf_token %}
        </div>
    </form>
</div>

{% endblock %}
</body>

{% block extrajs %}
<script>
$('#new_password').on('keyup', function () {
    if ( $(this).val() != "" ){
        $('#pwEnter').attr('class', 'glyphicon glyphicon-ok-circle').css('color', 'green');
    } else $(('#pwEnter').attr('class', ''));
});

$('#confirm_password').on('keyup', function () {
    if ($(this).val() == $('#new_password').val()) {
        $('#pwAlert').attr('class', 'glyphicon glyphicon-ok-circle').css('color', 'green');
    } else $('#pwAlert').attr('class', 'glyphicon glyphicon-remove-circle').css('color', 'red');
});
</script>
{% endblock %}
</html>

Netsweeper/NetsweeperCompetitors/templates/NetsweeperCompetitors/channels.html
<!DOCTYPE html>

<html>

{% extends "NetsweeperCompetitors/navbar.html" %}
<head lang="en">
    <meta charset="UTF-8">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Netsweeper Competitors</title>
    {% block extrastyles %}
    {% endblock %}

</head>
<body>
{% block body %}
<div id="messages">
    <p class="bg-danger text-danger" align="center">{{ message }}</p>
    <p class="small" align="center">Only companies with data in at least one field will be shown by default</p>
</div>
<div class="text-center" style="padding: 3%">
    <button class="btn btn-lg btn-primary" type="button" data-toggle="collapse" data-target="#collapseMe" aria-expanded="false" aria-controls="collapseMe">
        Filter Results
    </button>
</div>


<div class="collapse" id="collapseMe">
    <div class="selectForm" align="center">
        <form method="POST" action="{% url 'channels' %}">
            <div class="col-md-4 col-md-offset-2">
                {% csrf_token %}
                {{ form.selection.errors }}<br>
                {{ form.selection.label_tag }}<br>
                {{ form.selection }}
            </div>
            <div class="col-md-4">
                {{ form.graphType.errors }}<br>
                {{ form.graphType.label_tag }}<br>
                {{ form.graphType }}
            </div>
            <div class="col-md-12">
                <button type="submit" class="btn btn-lg btn-primary" id="formButtons">Submit</button>
                <a type="button" class="btn btn-lg btn-default" href="{% url 'channels' %}" id="formButtons">Clear Selections</a>
            </div>
        </form>
    </div>
</div>


<div id="graphContainer" style="width:100%; height:400px;"></div>


{% endblock %}
</body>

{% block extrajs %}
<script>
    $(function () {
    $('#graphContainer').highcharts({
        chart: {
            type: '{{ graph }}'
        },
        title: {
            text: 'Channels'
        },
        xAxis: {
            categories: [{% for item in channelValues %}'{{item.name}}', {% endfor %}]
        },
        yAxis: {
            title: {
                text: 'Percentage'
            }
        },
        plotOptions: {
            {{ graph }}: {
                dataLabels: {
                    enabled: false
                },
                enableMouseTracking: true
            }
        },
        series: [{
            name: 'Direct',
            data: [{% for item in channelValues %}{{item.direct}}, {% endfor %}]
        }, {
            name: 'Partners',
            data: [{% for item in channelValues %}{{item.partners}}, {% endfor %}]
        }]
    });
});
</script>

{% endblock %}
</html>

Netsweeper/NetsweeperCompetitors/templates/NetsweeperCompetitors/competitordocs.html
<!DOCTYPE html>

<html>

{% extends "NetsweeperCompetitors/navbar.html" %}
{% load dictionary_lookup %}
<head lang="en">
    <meta charset="UTF-8">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Netsweeper Competitors</title>
    {% block extrastyles %}
    <style>
        table { border: none !important; table-layout: fixed !important; }
        th, td { border: none !important;}
    </style>
    {% endblock %}
</head>
<body>
{% block body %}
<p class="bg-danger text-danger" align="center">{{ message }}</p>

<h3 class="text-center">Additional Competitor Information</h3>
<p class="text-center small">All documents are provided in PDF format</p>

<div class="text-center" style="padding: 3%">
    <button class="btn btn-lg btn-primary" type="button" data-toggle="collapse" data-target="#collapseMe" aria-expanded="false" aria-controls="collapseMe">
        Filter Results
    </button>
</div>


<div class="collapse" id="collapseMe">
    <div class="selectForm" align="center">
        <form method="POST" action="{% url 'competitordocs' %}">
            <div class="col-md-4 col-md-offset-4">
                {{ form.selection.errors }}<br>
                {{ form.selection.label_tag }}<br>
                {{ form.selection }}<br>
            </div>
            <div class="col-md-12">
                <button type="submit" class="btn btn-lg btn-primary" id="formButtons">Submit</button>
                <a type="button" class="btn btn-lg btn-default" href="{% url 'competitordocs' %}" id="formButtons">Clear Selections</a>
                {% csrf_token %}
            </div>
        </form>
    </div>
</div>


<table class="table table-hover" align="center">
    <tr>
        <td width="27%"></td>
        <td width="58%"></td>
        <td width="15%"></td>
    </tr>
    {% for key in files %}
    <tr class="info">
        <th colspan="3">
            <h4>{{ key }}</h4>
        </th>
    </tr>
    {% for item in files|get_item:key %}
    <tr>
        <td>
            <b>{{ item.document_name }}</b>
        </td>
        <td>
            <p>{{ item.description|linebreaks }}</p>
        </td>
        <td>
            <a href="{{ item.document.url }}" type="button" class="btn btn-primary">View</a>
        </td>
    </tr>
    {% endfor %}
    {% endfor %}
</table>

{% endblock %}
</body>

{% block extrajs %}


{% endblock %}
</html>

Netsweeper/NetsweeperCompetitors/templates/NetsweeperCompetitors/index.html
<!DOCTYPE html>

<html>

{% extends "NetsweeperCompetitors/navbar.html" %}
<head lang="en">
    <meta charset="UTF-8">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Netsweeper Competitors</title>
    {% block extrastyles %}
    {% endblock %}
</head>
<body>
{% block body %}

<h1 align="center">Netsweeper Competitors Data Analysis</h1>
<p class="lead" align="center">Select a category above to view and filter data visualizations<br><br>or</p>

<div align="center">
    <a href="{% url 'printpage'%}" type="button" class="btn btn-lg btn-primary">Print Competitor Datasheet</a>
</div>


{% endblock %}
</body>

{% block extrajs %}


{% endblock %}
</html>

Netsweeper/NetsweeperCompetitors/templates/NetsweeperCompetitors/printpage.html
<!DOCTYPE html>

<html>
{% extends "NetsweeperCompetitors/navbar.html" %}
{% load staticfiles %}

<head lang="en">
    <meta charset="UTF-8">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Netsweeper Competitors</title>
    {% block extrastyles %}
    {% endblock %}
</head>
<body>
{% block body %}
<div id="messages">
    <p class="bg-danger text-danger text-center" style="margin-top: 5%">{{ message }}</p>
</div>
<div class="selectForm" align="center">
    <form method="POST" action="{% url 'printpage' %}">
        {% csrf_token %}
        {{ form.selection.errors }}<br>
        {{ form.selection.label_tag }}<br>
        {{ form.selection }}
        {{ form.showCategories.errors }}<br>
        {{ form.showCategories }}
        {{ form.showCategories.label_tag }}
        {{ form.showPartners.errors }}
        {{ form.showPartners }}
        {{ form.showPartners.label_tag }}<br>

        <button type="submit" class="btn btn-lg btn-primary" id="formButtons">Submit</button>
        <a type="button" class="btn btn-lg btn-default" href="{% url 'printpage' %}" id="formButtons">Clear Selections</a>
    </form>
</div>
<div align="center">

    <form>
        <button class="btn btn-lg btn-primary" onClick="window.print()">Print</button>
    </form>
</div>
{% if competitor %}
<div>
    <h1 class="text-center">Netsweeper Competitor Datasheet</h1>
    <h2>
        {{ competitor.name }}
    </h2>
    <div class="row">
        <div class="col-xs-4">
            <p class="lead">Summary</p>
            {% if competitor.acquired %}
            <p><b>Acquired By: </b>{{ competitor.acquired_by }}</p>
            {% elif competitor.merged_with %}
            <p><b>Merged with: </b>{{ competitor.merged_with }}</p>
            {% endif %}

            <b>URL: </b>
            {% if competitor.url %}
            <p>{{ competitor.url }}</p>
            {% else %}
            <p>No data</p>
            {% endif %}

            <h4>Global Market Breakdown</h4 >
            {% if competitor.globalMarket %}
            {% for item in competitor.globalmarketshare_set.all %}
            <p><b>{{ item.global_market.name }}: </b>
                {% if item.share != 0.00 %}
                {{ item.share }}%</p>
            {% else %}
            Portion Unknown</p>
            {% endif %}
            {% endfor %}
            {% endif %}

            <h4>Vertical Market Breakdown</h4>
            {% if competitor.globalMarket %}
            {% for item in competitor.verticalmarketshare_set.all %}
            <p><b>{{ item.vertical_market.name }}: </b>
                {% if item.share != 0.00 %}
                {{ item.share }}%</p>
            {% else %}
            Portion Unknown</p>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div><!--col -->

        <div class="col-xs-4">
            <h4>Product Details</h4>

            {% for product in products %}

            <p> <b>Product Name: </b>{{ product.name }}</p>
            <p><b>Target Market: </b>
                {% if competitor.target_Market.name %}
                {{ competitor.target_Market.name }}
                {% else %}
                No data
                {% endif %}
            </p>
            <p><b>Price: </b>
                {% if product.price %}
                ${{ product.price }}
                {% else %}
                No data
                {% endif %}
            </p>
            <p><b>Filtering Categories: </b>
                {% if competitor.number_of_categories %}
                {{ competitor.number_of_categories }}
                {% else %}
                No data
                {% endif %}
            </p>
            <p><b>URL Database: </b>
                {% if product.urlDB %}
                {{ product.urlDB }}
                {% else %}
                No data
                {% endif %}
            </p>

            <p><b>Supported Platforms: </b>
                {% if product.platform %}
                {% for item in product.platform.all %}
                {{ item.name }}
                {% endfor %}
                {% else %}
                No data
                {% endif %}</p>

            <h4>SaaS/Appliance Breakdown</h4>

            <p><b>SaaS: </b>
                {% if competitor.saas %}
                {{ competitor.saas }}%
                {% else %}
                No data
                {% endif %}
            </p>

            <p><b>Appliance: </b>
                {% if competitor.appliance %}
                {{ competitor.appliance }}%
                {% else %}
                No data
                {% endif %}
            </p>
            {% empty %}
            <p>No product information available</p>
            {% endfor %}<!--for product in products -->
        </div><!--col -->

        <div class="col-xs-4">
            <h4>Strengths</h4>
            {% if competitor.strengths %}
            <p>{{ competitor.strengths|safe }}</p>
            {% else %}
            <p>No data</p>
            {% endif %}
            <h4>Weaknesses</h4>
            {% if competitor.weaknesses %}
            <p>{{ competitor.weaknesses|safe }}</p>
            {% else %}
            <p>No data</p>
            {% endif %}
            <h4>Notes</h4>
            <p>{{ competitor.notes }}</p>
        </div><!--col -->
    </div><!--Row -->
    <div class="row" id="features">
        <h2>Product Features</h2>
        {% for item in competitor.features.all %}
        <div class="col-xs-3">
            <p>{{ item.name }}</p>
        </div>
        {% empty %}
        <p>No feature data</p>
        {% endfor %}
    </div><!--Row/features -->
    {% if showCategories %}
    <div class="row" id="categories">
        <h2>{{ competitor.name }} Web Filtering Categories</h2>
        {% for item in competitor.competitorcategories_set.all %}

        <div class="col-xs-4">
            <p><b>{{ item.category.name}}</b></p><p>{{ item.details|safe }}</p>
        </div>
        {% empty %}
        <p>No category data</p>
        {% endfor %}
    </div><!--categories -->
    {% endif %}<!--if showCategories -->
    {% if showPartners %}
    <h2>{{ competitor.name }} Partnerships</h2>
    <div class="col-xs-4">
        <h4>Channel  Partners</h4>
        {% if competitor.channel_partners %}
        <p>{{ competitor.channel_partners|safe }}</p>
        {% else %}
        <p>None</p>
        {% endif %}
    </div><!--col -->
    <div class="col-xs-4">
        <h4>Technology  Partners</h4>
        {% if competitor.technology_partners %}
        <p>{{ competitor.technology_partners|safe }}</p>
        {% else %}
        <p>None</p>
        {% endif %}
    </div><!--col -->
    <div class="col-xs-4">
        <h4>OEM</h4>
        {% if competitor.oem_partners %}
        <p>{{ competitor.oem_partners|safe }}</p>
        {% else %}
        <p>None</p>
        {% endif %}
    </div><!--col -->
    {% endif %} <!--if showPartners -->
</div><!--Datasheet -->
{% endif %} <!--if competitor -->
{% endblock %}
</body>

{% block extrajs %}


{% endblock %}
</html>